
[server]
addr = "localhost"
port = "8080" 

[raft] 
addr = "127.0.0.1"
port = "12000"
peers = ["127.0.0.1:12000", "127.0.0.1:12001", "127.0.0.1:12002"]
peer_storage = "/tmp/raft0/raft_peer_storage"

[rpc] 
addr = "127.0.0.1"
port = "32123"

[log] 

log_dir = "/tmp/raft0" 
log_name = "raft_access_log" 