
[server]
addr = "localhost"
port = "8080" 

[raft] 
addr = "127.0.0.1"
port = "12000"
peers = ["127.0.0.1:12000"]
peer_storage = "raft0/raft_peer_storage"
enable_single_node = false 

[rpc] 
addr = "127.0.0.1"
port = "32123"

[log] 

log_dir = "raft0/logs" 
log_name = "raft_access_log" 
