
[server]
addr = "localhost"
port = "8081" 

[raft] 
addr = "127.0.0.1"
port = "12001"
peers = ["127.0.0.1:12001"]
peer_storage = "raft1/raft_peer_storage"
enable_single_node = false

[rpc] 
addr = "127.0.0.1"
port = "32124"

[log] 

log_dir = "raft1/logs" 
log_name = "raft_access_log" 
