
[server]
addr = "localhost"
port = "8082" 

[raft] 
addr = "127.0.0.1"
port = "12002"
peers = ["127.0.0.1:12000", "127.0.0.1:12001", "127.0.0.1:12002"]
peer_storage = "/tmp/raft2/raft_peer_storage"
enable_single_node = true

[rpc] 
addr = "127.0.0.1"
port = "32125"

[log] 

log_dir = "/tmp/raft2" 
log_name = "raft_access_log" 
