
[server]
addr = "localhost"
port = "8083" 

[raft] 
addr = "127.0.0.1"
port = "12003"
peers = []
peer_storage = "raft3/raft_peer_storage"
enable_single_node = true 

[rpc] 
addr = "127.0.0.1"
port = "32126"

[log] 

log_dir = "raft3/logs" 
log_name = "raft_access_log" 
