
[server]
addr = "localhost"
port = "8080" 

[server_monitor]
addr = "localhost"
port = "3780"

[raft] 
addr = "127.0.0.1"
port = "12000"
peers = ["127.0.0.1:12000", "127.0.0.1:12001", "127.0.0.1:12002"]
peer_storage = "raft/raft_peer_storage"
snapshot_storage = "raft/raft_snapshot_storage"
store_backend = "boltdb"
storage_backend_path = "raft/storage_backend_path"
raft_log_path = "raft/raft_log_path"
apply_log_path = "raft/apply_log_path"
enable_single_node = true

[rpc] 
addr = "127.0.0.1"
port = "32123"

[log] 

log_dir = "/tmp/raft0" 
log_name = "raft_access_log"
log_level = "debug"
