
[server]
addr = "localhost"
port = "8080" 

[raft] 
addr = "127.0.0.1"
port = "12000"
peers = ["127.0.0.1:12000"]
peer_storage = "raft0/raft_peer_storage"
snapshot_storage = "raft0/raft_snapshot_storage"
store_backend = "boltdb"
storage_backend_path = "raft0/storage_backend_path"
raft_log_path = "raft0/raft_log_path"
apply_log_path = "raft0/apply_log_path"
enable_single_node = true 

[rpc] 
addr = "127.0.0.1"
port = "32123"

[log] 

log_dir = "raft0/logs" 
log_name = "raft_access_log" 
