
[server]
addr = "localhost"
port = "8084" 

[raft] 
addr = "127.0.0.1"
port = "12004"
peers = []
peer_storage = "raft4/raft_peer_storage"
snapshot_storage = "raft4/raft_snapshot_storage"
enable_single_node = true 

[rpc] 
addr = "127.0.0.1"
port = "32127"

[log] 

log_dir = "raft4/logs" 
log_name = "raft_access_log" 
